/*
 * This file is generated by jOOQ.
 */
package com.getreferral.client.jooq.tables.records;


import com.getreferral.client.jooq.tables.SpringSessionAttributes;
import com.getreferral.client.jooq.tables.interfaces.ISpringSessionAttributes;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpringSessionAttributesRecord extends UpdatableRecordImpl<SpringSessionAttributesRecord> implements ISpringSessionAttributes {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>jdbc_session.spring_session_attributes.SESSION_PRIMARY_ID</code>.
     */
    @Override
    public void setSessionPrimaryId(String value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>jdbc_session.spring_session_attributes.SESSION_PRIMARY_ID</code>.
     */
    @Override
    public String getSessionPrimaryId() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>jdbc_session.spring_session_attributes.ATTRIBUTE_NAME</code>.
     */
    @Override
    public void setAttributeName(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>jdbc_session.spring_session_attributes.ATTRIBUTE_NAME</code>.
     */
    @Override
    public String getAttributeName() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>jdbc_session.spring_session_attributes.ATTRIBUTE_BYTES</code>.
     */
    @Override
    public void setAttributeBytes(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>jdbc_session.spring_session_attributes.ATTRIBUTE_BYTES</code>.
     */
    @Override
    public byte[] getAttributeBytes() {
        return (byte[]) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ISpringSessionAttributes from) {
        setSessionPrimaryId(from.getSessionPrimaryId());
        setAttributeName(from.getAttributeName());
        setAttributeBytes(from.getAttributeBytes());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends ISpringSessionAttributes> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpringSessionAttributesRecord
     */
    public SpringSessionAttributesRecord() {
        super(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES);
    }

    /**
     * Create a detached, initialised SpringSessionAttributesRecord
     */
    public SpringSessionAttributesRecord(String sessionPrimaryId, String attributeName, byte[] attributeBytes) {
        super(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES);

        setSessionPrimaryId(sessionPrimaryId);
        setAttributeName(attributeName);
        setAttributeBytes(attributeBytes);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SpringSessionAttributesRecord
     */
    public SpringSessionAttributesRecord(com.getreferral.client.jooq.tables.pojos.SpringSessionAttributes value) {
        super(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES);

        if (value != null) {
            setSessionPrimaryId(value.getSessionPrimaryId());
            setAttributeName(value.getAttributeName());
            setAttributeBytes(value.getAttributeBytes());
            resetChangedOnNotNull();
        }
    }
}
