/*
 * This file is generated by jOOQ.
 */
package com.getreferral.client.jooq.tables.records;


import com.getreferral.client.jooq.tables.SpringSession;
import com.getreferral.client.jooq.tables.interfaces.ISpringSession;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpringSessionRecord extends UpdatableRecordImpl<SpringSessionRecord> implements ISpringSession {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>jdbc_session.spring_session.PRIMARY_ID</code>.
     */
    @Override
    public void setPrimaryId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>jdbc_session.spring_session.PRIMARY_ID</code>.
     */
    @Override
    public String getPrimaryId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>jdbc_session.spring_session.SESSION_ID</code>.
     */
    @Override
    public void setSessionId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jdbc_session.spring_session.SESSION_ID</code>.
     */
    @Override
    public String getSessionId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jdbc_session.spring_session.CREATION_TIME</code>.
     */
    @Override
    public void setCreationTime(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>jdbc_session.spring_session.CREATION_TIME</code>.
     */
    @Override
    public Long getCreationTime() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>jdbc_session.spring_session.LAST_ACCESS_TIME</code>.
     */
    @Override
    public void setLastAccessTime(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>jdbc_session.spring_session.LAST_ACCESS_TIME</code>.
     */
    @Override
    public Long getLastAccessTime() {
        return (Long) get(3);
    }

    /**
     * Setter for
     * <code>jdbc_session.spring_session.MAX_INACTIVE_INTERVAL</code>.
     */
    @Override
    public void setMaxInactiveInterval(Integer value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>jdbc_session.spring_session.MAX_INACTIVE_INTERVAL</code>.
     */
    @Override
    public Integer getMaxInactiveInterval() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>jdbc_session.spring_session.EXPIRY_TIME</code>.
     */
    @Override
    public void setExpiryTime(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>jdbc_session.spring_session.EXPIRY_TIME</code>.
     */
    @Override
    public Long getExpiryTime() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>jdbc_session.spring_session.PRINCIPAL_NAME</code>.
     */
    @Override
    public void setPrincipalName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>jdbc_session.spring_session.PRINCIPAL_NAME</code>.
     */
    @Override
    public String getPrincipalName() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ISpringSession from) {
        setPrimaryId(from.getPrimaryId());
        setSessionId(from.getSessionId());
        setCreationTime(from.getCreationTime());
        setLastAccessTime(from.getLastAccessTime());
        setMaxInactiveInterval(from.getMaxInactiveInterval());
        setExpiryTime(from.getExpiryTime());
        setPrincipalName(from.getPrincipalName());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends ISpringSession> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpringSessionRecord
     */
    public SpringSessionRecord() {
        super(SpringSession.SPRING_SESSION);
    }

    /**
     * Create a detached, initialised SpringSessionRecord
     */
    public SpringSessionRecord(String primaryId, String sessionId, Long creationTime, Long lastAccessTime, Integer maxInactiveInterval, Long expiryTime, String principalName) {
        super(SpringSession.SPRING_SESSION);

        setPrimaryId(primaryId);
        setSessionId(sessionId);
        setCreationTime(creationTime);
        setLastAccessTime(lastAccessTime);
        setMaxInactiveInterval(maxInactiveInterval);
        setExpiryTime(expiryTime);
        setPrincipalName(principalName);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SpringSessionRecord
     */
    public SpringSessionRecord(com.getreferral.client.jooq.tables.pojos.SpringSession value) {
        super(SpringSession.SPRING_SESSION);

        if (value != null) {
            setPrimaryId(value.getPrimaryId());
            setSessionId(value.getSessionId());
            setCreationTime(value.getCreationTime());
            setLastAccessTime(value.getLastAccessTime());
            setMaxInactiveInterval(value.getMaxInactiveInterval());
            setExpiryTime(value.getExpiryTime());
            setPrincipalName(value.getPrincipalName());
            resetChangedOnNotNull();
        }
    }
}
