/*
 * This file is generated by jOOQ.
 */
package com.getreferral.client.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public interface IFlywaySchemaHistory extends Serializable {

    /**
     * Setter for
     * <code>jdbc_session.flyway_schema_history.installed_rank</code>.
     */
    public void setInstalledRank(Integer value);

    /**
     * Getter for
     * <code>jdbc_session.flyway_schema_history.installed_rank</code>.
     */
    public Integer getInstalledRank();

    /**
     * Setter for <code>jdbc_session.flyway_schema_history.version</code>.
     */
    public void setVersion(String value);

    /**
     * Getter for <code>jdbc_session.flyway_schema_history.version</code>.
     */
    public String getVersion();

    /**
     * Setter for <code>jdbc_session.flyway_schema_history.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>jdbc_session.flyway_schema_history.description</code>.
     */
    public String getDescription();

    /**
     * Setter for <code>jdbc_session.flyway_schema_history.type</code>.
     */
    public void setType(String value);

    /**
     * Getter for <code>jdbc_session.flyway_schema_history.type</code>.
     */
    public String getType();

    /**
     * Setter for <code>jdbc_session.flyway_schema_history.script</code>.
     */
    public void setScript(String value);

    /**
     * Getter for <code>jdbc_session.flyway_schema_history.script</code>.
     */
    public String getScript();

    /**
     * Setter for <code>jdbc_session.flyway_schema_history.checksum</code>.
     */
    public void setChecksum(Integer value);

    /**
     * Getter for <code>jdbc_session.flyway_schema_history.checksum</code>.
     */
    public Integer getChecksum();

    /**
     * Setter for <code>jdbc_session.flyway_schema_history.installed_by</code>.
     */
    public void setInstalledBy(String value);

    /**
     * Getter for <code>jdbc_session.flyway_schema_history.installed_by</code>.
     */
    public String getInstalledBy();

    /**
     * Setter for <code>jdbc_session.flyway_schema_history.installed_on</code>.
     */
    public void setInstalledOn(LocalDateTime value);

    /**
     * Getter for <code>jdbc_session.flyway_schema_history.installed_on</code>.
     */
    public LocalDateTime getInstalledOn();

    /**
     * Setter for
     * <code>jdbc_session.flyway_schema_history.execution_time</code>.
     */
    public void setExecutionTime(Integer value);

    /**
     * Getter for
     * <code>jdbc_session.flyway_schema_history.execution_time</code>.
     */
    public Integer getExecutionTime();

    /**
     * Setter for <code>jdbc_session.flyway_schema_history.success</code>.
     */
    public void setSuccess(Byte value);

    /**
     * Getter for <code>jdbc_session.flyway_schema_history.success</code>.
     */
    public Byte getSuccess();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IFlywaySchemaHistory
     */
    public void from(IFlywaySchemaHistory from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IFlywaySchemaHistory
     */
    public <E extends IFlywaySchemaHistory> E into(E into);
}
