/*
 * This file is generated by jOOQ.
 */
package com.getreferral.client.jooq.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public interface ISpringSession extends Serializable {

    /**
     * Setter for <code>jdbc_session.spring_session.PRIMARY_ID</code>.
     */
    public void setPrimaryId(String value);

    /**
     * Getter for <code>jdbc_session.spring_session.PRIMARY_ID</code>.
     */
    public String getPrimaryId();

    /**
     * Setter for <code>jdbc_session.spring_session.SESSION_ID</code>.
     */
    public void setSessionId(String value);

    /**
     * Getter for <code>jdbc_session.spring_session.SESSION_ID</code>.
     */
    public String getSessionId();

    /**
     * Setter for <code>jdbc_session.spring_session.CREATION_TIME</code>.
     */
    public void setCreationTime(Long value);

    /**
     * Getter for <code>jdbc_session.spring_session.CREATION_TIME</code>.
     */
    public Long getCreationTime();

    /**
     * Setter for <code>jdbc_session.spring_session.LAST_ACCESS_TIME</code>.
     */
    public void setLastAccessTime(Long value);

    /**
     * Getter for <code>jdbc_session.spring_session.LAST_ACCESS_TIME</code>.
     */
    public Long getLastAccessTime();

    /**
     * Setter for
     * <code>jdbc_session.spring_session.MAX_INACTIVE_INTERVAL</code>.
     */
    public void setMaxInactiveInterval(Integer value);

    /**
     * Getter for
     * <code>jdbc_session.spring_session.MAX_INACTIVE_INTERVAL</code>.
     */
    public Integer getMaxInactiveInterval();

    /**
     * Setter for <code>jdbc_session.spring_session.EXPIRY_TIME</code>.
     */
    public void setExpiryTime(Long value);

    /**
     * Getter for <code>jdbc_session.spring_session.EXPIRY_TIME</code>.
     */
    public Long getExpiryTime();

    /**
     * Setter for <code>jdbc_session.spring_session.PRINCIPAL_NAME</code>.
     */
    public void setPrincipalName(String value);

    /**
     * Getter for <code>jdbc_session.spring_session.PRINCIPAL_NAME</code>.
     */
    public String getPrincipalName();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface ISpringSession
     */
    public void from(ISpringSession from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface ISpringSession
     */
    public <E extends ISpringSession> E into(E into);
}
