/*
 * This file is generated by jOOQ.
 */
package com.getreferral.client.jooq.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public interface ISpringSessionAttributes extends Serializable {

    /**
     * Setter for
     * <code>jdbc_session.spring_session_attributes.SESSION_PRIMARY_ID</code>.
     */
    public void setSessionPrimaryId(String value);

    /**
     * Getter for
     * <code>jdbc_session.spring_session_attributes.SESSION_PRIMARY_ID</code>.
     */
    public String getSessionPrimaryId();

    /**
     * Setter for
     * <code>jdbc_session.spring_session_attributes.ATTRIBUTE_NAME</code>.
     */
    public void setAttributeName(String value);

    /**
     * Getter for
     * <code>jdbc_session.spring_session_attributes.ATTRIBUTE_NAME</code>.
     */
    public String getAttributeName();

    /**
     * Setter for
     * <code>jdbc_session.spring_session_attributes.ATTRIBUTE_BYTES</code>.
     */
    public void setAttributeBytes(byte[] value);

    /**
     * Getter for
     * <code>jdbc_session.spring_session_attributes.ATTRIBUTE_BYTES</code>.
     */
    public byte[] getAttributeBytes();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface ISpringSessionAttributes
     */
    public void from(ISpringSessionAttributes from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface ISpringSessionAttributes
     */
    public <E extends ISpringSessionAttributes> E into(E into);
}
