/*
 * This file is generated by jOOQ.
 */
package com.getreferral.client.jooq;


import com.getreferral.client.jooq.tables.FlywaySchemaHistory;
import com.getreferral.client.jooq.tables.SpringSession;
import com.getreferral.client.jooq.tables.SpringSessionAttributes;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JdbcSession extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>jdbc_session</code>
     */
    public static final JdbcSession JDBC_SESSION = new JdbcSession();

    /**
     * The table <code>jdbc_session.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>jdbc_session.spring_session</code>.
     */
    public final SpringSession SPRING_SESSION = SpringSession.SPRING_SESSION;

    /**
     * The table <code>jdbc_session.spring_session_attributes</code>.
     */
    public final SpringSessionAttributes SPRING_SESSION_ATTRIBUTES = SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES;

    /**
     * No further instances allowed
     */
    private JdbcSession() {
        super("jdbc_session", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            SpringSession.SPRING_SESSION,
            SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES
        );
    }
}
