/*
 * This file is generated by jOOQ.
 */
package com.getreferral.client.jooq;


import com.getreferral.client.jooq.tables.FlywaySchemaHistory;
import com.getreferral.client.jooq.tables.SpringSession;
import com.getreferral.client.jooq.tables.SpringSessionAttributes;


/**
 * Convenience access to all tables in jdbc_session.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>jdbc_session.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>jdbc_session.spring_session</code>.
     */
    public static final SpringSession SPRING_SESSION = SpringSession.SPRING_SESSION;

    /**
     * The table <code>jdbc_session.spring_session_attributes</code>.
     */
    public static final SpringSessionAttributes SPRING_SESSION_ATTRIBUTES = SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES;
}
