/*
 * This file is generated by jOOQ.
 */
package com.getreferral.client.jooq.tables.pojos;


import com.getreferral.client.jooq.tables.interfaces.ISpringSession;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpringSession implements ISpringSession {

    private static final long serialVersionUID = 1L;

    private String primaryId;
    private String sessionId;
    private Long creationTime;
    private Long lastAccessTime;
    private Integer maxInactiveInterval;
    private Long expiryTime;
    private String principalName;

    public SpringSession() {}

    public SpringSession(ISpringSession value) {
        this.primaryId = value.getPrimaryId();
        this.sessionId = value.getSessionId();
        this.creationTime = value.getCreationTime();
        this.lastAccessTime = value.getLastAccessTime();
        this.maxInactiveInterval = value.getMaxInactiveInterval();
        this.expiryTime = value.getExpiryTime();
        this.principalName = value.getPrincipalName();
    }

    public SpringSession(
        String primaryId,
        String sessionId,
        Long creationTime,
        Long lastAccessTime,
        Integer maxInactiveInterval,
        Long expiryTime,
        String principalName
    ) {
        this.primaryId = primaryId;
        this.sessionId = sessionId;
        this.creationTime = creationTime;
        this.lastAccessTime = lastAccessTime;
        this.maxInactiveInterval = maxInactiveInterval;
        this.expiryTime = expiryTime;
        this.principalName = principalName;
    }

    /**
     * Getter for <code>jdbc_session.spring_session.PRIMARY_ID</code>.
     */
    @Override
    public String getPrimaryId() {
        return this.primaryId;
    }

    /**
     * Setter for <code>jdbc_session.spring_session.PRIMARY_ID</code>.
     */
    @Override
    public void setPrimaryId(String primaryId) {
        this.primaryId = primaryId;
    }

    /**
     * Getter for <code>jdbc_session.spring_session.SESSION_ID</code>.
     */
    @Override
    public String getSessionId() {
        return this.sessionId;
    }

    /**
     * Setter for <code>jdbc_session.spring_session.SESSION_ID</code>.
     */
    @Override
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * Getter for <code>jdbc_session.spring_session.CREATION_TIME</code>.
     */
    @Override
    public Long getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>jdbc_session.spring_session.CREATION_TIME</code>.
     */
    @Override
    public void setCreationTime(Long creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>jdbc_session.spring_session.LAST_ACCESS_TIME</code>.
     */
    @Override
    public Long getLastAccessTime() {
        return this.lastAccessTime;
    }

    /**
     * Setter for <code>jdbc_session.spring_session.LAST_ACCESS_TIME</code>.
     */
    @Override
    public void setLastAccessTime(Long lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    /**
     * Getter for
     * <code>jdbc_session.spring_session.MAX_INACTIVE_INTERVAL</code>.
     */
    @Override
    public Integer getMaxInactiveInterval() {
        return this.maxInactiveInterval;
    }

    /**
     * Setter for
     * <code>jdbc_session.spring_session.MAX_INACTIVE_INTERVAL</code>.
     */
    @Override
    public void setMaxInactiveInterval(Integer maxInactiveInterval) {
        this.maxInactiveInterval = maxInactiveInterval;
    }

    /**
     * Getter for <code>jdbc_session.spring_session.EXPIRY_TIME</code>.
     */
    @Override
    public Long getExpiryTime() {
        return this.expiryTime;
    }

    /**
     * Setter for <code>jdbc_session.spring_session.EXPIRY_TIME</code>.
     */
    @Override
    public void setExpiryTime(Long expiryTime) {
        this.expiryTime = expiryTime;
    }

    /**
     * Getter for <code>jdbc_session.spring_session.PRINCIPAL_NAME</code>.
     */
    @Override
    public String getPrincipalName() {
        return this.principalName;
    }

    /**
     * Setter for <code>jdbc_session.spring_session.PRINCIPAL_NAME</code>.
     */
    @Override
    public void setPrincipalName(String principalName) {
        this.principalName = principalName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SpringSession other = (SpringSession) obj;
        if (this.primaryId == null) {
            if (other.primaryId != null)
                return false;
        }
        else if (!this.primaryId.equals(other.primaryId))
            return false;
        if (this.sessionId == null) {
            if (other.sessionId != null)
                return false;
        }
        else if (!this.sessionId.equals(other.sessionId))
            return false;
        if (this.creationTime == null) {
            if (other.creationTime != null)
                return false;
        }
        else if (!this.creationTime.equals(other.creationTime))
            return false;
        if (this.lastAccessTime == null) {
            if (other.lastAccessTime != null)
                return false;
        }
        else if (!this.lastAccessTime.equals(other.lastAccessTime))
            return false;
        if (this.maxInactiveInterval == null) {
            if (other.maxInactiveInterval != null)
                return false;
        }
        else if (!this.maxInactiveInterval.equals(other.maxInactiveInterval))
            return false;
        if (this.expiryTime == null) {
            if (other.expiryTime != null)
                return false;
        }
        else if (!this.expiryTime.equals(other.expiryTime))
            return false;
        if (this.principalName == null) {
            if (other.principalName != null)
                return false;
        }
        else if (!this.principalName.equals(other.principalName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.primaryId == null) ? 0 : this.primaryId.hashCode());
        result = prime * result + ((this.sessionId == null) ? 0 : this.sessionId.hashCode());
        result = prime * result + ((this.creationTime == null) ? 0 : this.creationTime.hashCode());
        result = prime * result + ((this.lastAccessTime == null) ? 0 : this.lastAccessTime.hashCode());
        result = prime * result + ((this.maxInactiveInterval == null) ? 0 : this.maxInactiveInterval.hashCode());
        result = prime * result + ((this.expiryTime == null) ? 0 : this.expiryTime.hashCode());
        result = prime * result + ((this.principalName == null) ? 0 : this.principalName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SpringSession (");

        sb.append(primaryId);
        sb.append(", ").append(sessionId);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(lastAccessTime);
        sb.append(", ").append(maxInactiveInterval);
        sb.append(", ").append(expiryTime);
        sb.append(", ").append(principalName);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ISpringSession from) {
        setPrimaryId(from.getPrimaryId());
        setSessionId(from.getSessionId());
        setCreationTime(from.getCreationTime());
        setLastAccessTime(from.getLastAccessTime());
        setMaxInactiveInterval(from.getMaxInactiveInterval());
        setExpiryTime(from.getExpiryTime());
        setPrincipalName(from.getPrincipalName());
    }

    @Override
    public <E extends ISpringSession> E into(E into) {
        into.from(this);
        return into;
    }
}
